# Generated by Django 4.0.3 on 2024-05-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_parking_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='close_day',
            field=models.CharField(blank=True, default='없음', max_length=10, verbose_name='휴일'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='이미지 링크 목록'),
        ),
    ]
