# Generated by Django 4.0.3 on 2024-05-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_parking_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='parkign_longitude',
            field=models.FloatField(default='127.056090471223', null=True, verbose_name='위치 경도'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parking_latitude',
            field=models.FloatField(default='127.056090471223', null=True, verbose_name='주차장 위도'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price1',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='메인메뉴1 가격'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price2',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='메인메뉴2 가격'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title1',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='메인메뉴1 이름'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title2',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='메인메뉴2 이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 링크 목록'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='가게 소개'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(default='', null=True, verbose_name='메뉴 URL'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='parking_area',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='주차장소추천'),
        ),
    ]
